<?php

/* This file is generated by the open source Parm Generator. https://github.com/cassell/Parm */

namespace dao\empresacrudDatabase;

interface ClienteTable
{
    const ID_COLUMN = 'id';
    const NOMBRES_COLUMN = 'nombres';
    const CIUDAD_COLUMN = 'ciudad';
    const SEXO_COLUMN = 'sexo';
    const TELEFONO_COLUMN = 'telefono';
    const FECHA_NACIMIENTO_COLUMN = 'fecha_nacimiento';

}