<?php

/* This file is generated by the open source Parm Generator. github.com/cassell/Parm */

namespace dao\empresacrudDatabase;

trait ClienteTableFunctions
{
    /**
     * Get the "logical" table name associated. The configuration can point to a different database name.
     * @return string
     */
    static function getDatabaseName()
    {
        return 'empresacrud';
    }

    /**
     * Get the table name associated with this object
     * @return string
     */
    public static function getTableName()
    {
        return 'cliente';
    }

    /**
     * Get the column name of the primary key field
     * @return string The primary key column name
     */
    public static function getIdField()
    {
        return ClienteTable::ID_COLUMN;
    }

    /**
     * Get the factory associated with this object
     * @return ClienteDaoFactory A DAO Factory
     */
    static function getFactory(\Doctrine\DBAL\Connection $connection = null)
    {
        return new ClienteDaoFactory($connection);
    }


    
    /**
     * Get the list of columns in cliente from logical database "empresacrud"
     * @return Array Array of field names
     */
    public static function getFields()
    {
        return array(ClienteTable::ID_COLUMN, ClienteTable::NOMBRES_COLUMN, ClienteTable::CIUDAD_COLUMN, ClienteTable::SEXO_COLUMN, ClienteTable::TELEFONO_COLUMN, ClienteTable::FECHA_NACIMIENTO_COLUMN);
    }

    /**
     * Load an object associated with this factory
     * @return ClienteDaoObject An object built from a row out of the database table
     */
    public function loadDataObject(Array $row)
    {
        return new ClienteDaoObject($row);
    }
    
    public final static function getDefaultRow()
    {
        return array(ClienteTable::ID_COLUMN => null, ClienteTable::NOMBRES_COLUMN => null, ClienteTable::CIUDAD_COLUMN => null, ClienteTable::SEXO_COLUMN => null, ClienteTable::TELEFONO_COLUMN => null, ClienteTable::FECHA_NACIMIENTO_COLUMN => null);
    }

}
